---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: proxy
spec:
  clusterIP: None
  selector:
    type: proxy
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-bluestatefulset
  labels:
    type: proxy
spec:
  replicas: 2
  serviceName: nginx-service
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
...              
