---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: db
    author: prabhanjan
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: postgres-pod
      labels:
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: prabhanjan
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: mydb
...                
