---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: prabhu-ns
  labels:
    author: prabhanjan
spec:
  containers:
    - name: myghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
      ports:
        - containerPort: 2368
          hostPort: 9090
...            
