---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    author: prabhanjan
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
       type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx:1.26
...
