---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels: 
   type: db
   author: prabhanjan
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    type: db
...

