---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels: 
   type: db
   author: prabhanjan
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: db
    author: prabhanjan
...

