---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels: 
   type: db
   author: prabhanjan
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008  
  selector:
    type: proxy
    author: prabhanjan
...

