---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    author: intelliqit
spec:
  selector: 
   type: localrepo
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 31000

