---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: prabhanjan
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxy
    author: Prabhanjan
...      
