---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    type: db
spec:
  clusterIP: None
  selector:
    type: db
  ports:
    - port: 3306
      name: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-st
  labels:
    type: db
spec:
  replicas: 3
  serviceName: mysql-service
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              name: database
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
...


