---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: proxy
spec:
  clusterIP: None
  selector:
    type: proxy
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-st
  labels:
    type: proxy
spec:
  replicas: 3
  serviceName: nginx-service
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: myvolume
              mountPath: /usr/share/nginx/html/
  volumeClaimTemplates:
    - metadata:
        name: myvolume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
...
