---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: webserver
spec:
  containers:
    - name: tomcat
      image: tomee
  tolerations:
    - key: slave1
      operator: Equal
      value: worker1
      effect: NoSchedule
...        
