---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: '12345'
      tolerations:
        - key: slave3
          operator: Equal
          value: worker3
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slave3
                    operator: In
                    values:
                      - worker3
...

