---
version: "3"
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Prabhanjan
    deploy:
      replicas: 2
  wordpress:
    image: wordpress
    ports:
      - 9090:80
    deploy:
      replicas: 3
...

